on: 
  push:
    branches:
      - main

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
    #PIC16F877A
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F877A
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/8fd6b64f31d32eb7adfc1cfdd6bb330a
          gist_title: Pr치ctica 16 - Sensor de temperatura DS18B20 PIC16F877A CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F877A/Sensor de temperatura DS18B20.c
          file_encoding: WINDOWS-1252
    #PIC16F887
      - name: Checkout
        uses: actions/checkout@v2
      - uses: vhperaltaj/gist-sync-action@v1.0.0
        id: PIC16F887
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/microside-mx/02fba9f4bd30a8ab33d6f6b2e537f733
          gist_title: Pr치ctica 16 - Sensor de temperatura DS18B20 PIC16F887 CCS.c
          gist_description: Pr치cticas PIC CCS
          github_file: Proyecto/PIC16F887/Sensor de temperatura DS18B20.c
          file_encoding: WINDOWS-1252